version: "3.8"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_ROOT_USER}
      - POSTGRES_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: tubes2-gitulah/backend
    build:
      context: ./src/backend
    restart: always
    environment:
      - DATABASE_ADDRESS=${DATABASE_ADDRESS}
      - DATABASE_USER=${DATABASE_ROOT_USER}
      - DATABASE_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
    depends_on:
      - database
    ports:
      - 5761:5761

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - ${FRONTEND_HOST_PORT:-3000}:3000
    depends_on:
      - backend

volumes:
  pgdata:
